version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: claims_postgres
    ports:
      - "5447:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: employee_claims_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: claims_backend
    ports:
      - "3013:3013"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin234
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: employee_claims_db

  employee-side-claim:
    build: ./employee-side-claim
    container_name: claims_employee_ui
    ports:
      - "8022:80"
    depends_on:
      - backend

  hr-claim:
    build: ./hr-claim
    container_name: claims_hr_ui
    ports:
      - "8023:80"
    depends_on:
      - backend

volumes:
  pgdata:

